# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Tinui Heritage Objects Collection'
description:      'The Tinui Museum Collection spans over 150 years of rural life in New Zealand.'
url:              'https://kshepherd.github.io'
baseurl:          '/tinui-website-demo-002'
copyright:        'Copyright Tinui Museum 2023'
logo:             '/assets/postoffice.png'
default_thumb:    '/assets/default.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude: ["Gemfile*", "*.gemspec", "Rakefile", "vendor", "spec", "README.md", "LICENSE.txt", "Docker*"]
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
#  qatar: # name of collection
#    output: true # makes sure pages are output as html files
#    layout: 'qatar_item' # the layout for the pages to use
#    metadata:
#      source: 'qatar.csv' # path to the metadata file within `_data`
#    images:
#      source: 'raw_images/qatar' # path to the directory of images within `_data`
  tinui: # name of collection
    output: true
    layout: 'tinui_item'
    metadata:
      source: 'tinui.csv'
    images:
      source: 'raw_images/tinui'
# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
#      qatar:
#        content: false # whether or not to index page content
#        fields: # the metadata fields to index
#          - artist
#          - location
#          - label
#          - _date
#          - object_type
#          - current_location
      tinui:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - subjects
          - collector
          - creator
          - description
          - extent
          - condition
          - materials
          - notes
          - pid
          - archive_number
# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'About'
    sub:
      - label: 'Wax'
        link: '/about/'
      - label: 'Documentation'
        link: 'https://minicomp.github.io/wiki/wax/'
      - label: 'Credits'
        link: '/credits/'
  - label: 'Reports and Exhibitions'
    sub:
      - label: 'Significance Reports 2023'
        link: '/significance-reports-2023/'
  - label: 'Browse'
    link: '/collection/'
  - label: 'Search'
    link: '/search/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/minicomp/wax'
    - label: 'Credits'
      link: '/credits'
    - label: 'Wiki'
      link: 'https://minicomp.github.io/wiki/wax/'
  logos:
    - img: '/assets/postoffice.jpg'

# FIN
